### ISSUE TITLE
Capacitor 6 support

### ISSUE THREAD

**Issue by cardacci** [capacitor-community/native-audio#102]
Hi there! I'm interested in using this plugin with[ Capacitor 6](https://github.com/ionic-team/capacitor). Are there any plans to adapt it for compatibility with Capacitor 6? Thanks!

**Comment by bondulich** [comment]
I have a fork with support for Capacitor v6

https://github.com/bondulich/native-audio

**Comment by jldlxs** [comment]
Suggestion: change the pod spec name to 'BondulichNativeAudio' in the pod file. When deploying to iOS It throws an error because the name in the PodFile doesn't match with the name in the file inside node_modules. In the node_modules file it is 'CapacitorCommunityNativeAudio'.

**Comment by bondulich** [comment]
Hi @jldlxs  thanks, I already fixed the plugin

**Comment by jcesarmobile** [comment]
published 6.0.0 with Capacitor 6 support
