### ISSUE TITLE
[Bug] Sound stop does not work on iOS

### ISSUE THREAD

**Issue by yacut** [capacitor-community/native-audio#14]
**Describe the bug**
The sound does not stop on iOS after calling the stop method

**To Reproduce**

```js
import { Plugins } from "@capacitor/core";

const { NativeAudio } = Plugins;

NativeAudio.preloadSimple({
  assetPath: "audio/chime.mp3",
  assetId: "chime_audio",
});

NativeAudio.play({
  assetId: "chime_audio",
});

setTimeout(() =>
  NativeAudio.stop({
    assetId: "chime_audio",
  })
, 500);
```

**Expected behavior**
Sound stops to play

**Actual behavior**
Sound continues to play

**Smartphone:**
 - Device: iPhone SE simulator
 - OS: iOS13.6
 - Version 0.1.3

**Comment by kheftel** [comment]
`stop` on iOS only works on sounds loaded with `preloadComplex`.

For sounds loaded with `preloadSimple`, you can see [here](https://github.com/capacitor-community/native-audio/blob/master/ios/Plugin/Plugin.swift#L88) that it's using `AudioServicesPlaySystemSound`, and I don't see anything in [Apple's documentation](https://developer.apple.com/documentation/audiotoolbox/1405248-audioservicesplaysystemsound) about being able to stop them.

from the documentation:

```
Sound files that you play using this function must be:

No longer than 30 seconds in duration

In linear PCM or IMA4 (IMA/ADPCM) format

Packaged in a .caf, .aif, or .wav file

In addition, when you use the AudioServicesPlaySystemSound function:

Sounds play at the current system audio volume, with no programmatic volume control available

Sounds play immediately

Looping and stereo positioning are unavailable

Simultaneous playback is unavailable: You can play only one sound at a time

The sound is played locally on the device speakers; it does not use audio routing.
```

**Comment by yacut** [comment]
I can confirm that it works. Thank you @kheftel 

```js
import { Plugins } from "@capacitor/core";

const { NativeAudio } = Plugins;

NativeAudio.preloadComplex({
  assetPath: "audio/chime.mp3",
  assetId: "chime_audio",
});

NativeAudio.play({
  assetId: "chime_audio",
});

setTimeout(() =>
  NativeAudio.stop({
    assetId: "chime_audio",
  })
, 500);
```
