### ISSUE TITLE
Wrong path to NativeAudio in README

### ISSUE THREAD

**Issue by SmallhillCZ** [capacitor-community/native-audio#15]
**Describe the bug**
The import path in README.md (`import com.getcapacitor.community.audio.nativeaudio.NativeAudio;`) doesn't exist.

**To Reproduce**
1. `npm install @capacitor-community/native-audio`
2. `npx cap sync`
3. Add plugin to MainActivity as described in README.md
4. Open Android Studio and try to build the project.
5. See error saying the NativeAudio token doesn't exist.

**Expected behavior**
Path in README.md should probably be `import com.getcapacitor.community.audio.NativeAudio;`
No error! :)

**Comment by taylorchance** [comment]
Yup I had this exact error
