### ISSUE TITLE
Cannot find com.getcapacitor.community.audio.nativeaudio.NativeAudio;

### ISSUE THREAD

**Issue by leafiy** [capacitor-community/native-audio#17]
**Describe the bug**
Cannot find com.getcapacitor.community.audio.nativeaudio.NativeAudio;

**To Reproduce**
Run my app in Android studio

**Screenshots**
![image](https://user-images.githubusercontent.com/870449/101221816-6b339f80-36c3-11eb-944e-fadfbd680453.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.01
 - Version Capacitor

**Smartphone (please complete the following information):**
 - Android stuido 4.1.1

**Comment by bdsimmons** [comment]
I experienced the same issue. After working with the ionic team my issue was fixed after running: 

`File -> Sync Project with Gradle Files from the menubar.`

**HOWEVER**, the import statement in the docs did not work for me after that. The docs say:

`import com.getcapacitor.community.audio.nativeaudio.NativeAudio;`

I had to use:

`import com.getcapacitor.community.audio.NativeAudio;`

After this, building is working for me.
