### ISSUE TITLE
Not working real iPhone

### ISSUE THREAD

**Issue by JuanNitram** [capacitor-community/native-audio#21]
As the title said, I was trying to make it work on a real phone but I couldn't. Everything is working fine when I test the app on the simulator but there's no way to make it work on a real phone.

Does anyone have this problem? Which are the possible solutions?

**Comment by kheftel** [comment]
this may not help you much, but, it's working in my app based on my pull request (https://github.com/capacitor-community/native-audio/pull/10), i actually have it installed based on git url of my fork (https://github.com/kheftel/native-audio/tree/new-features)

`"@capacitor-community/native-audio": "git+https://github.com/kheftel/native-audio.git#new-features",` is the line in my package.json.

still waiting for PR to be merged.

**Comment by bazuka5801** [comment]
@kheftel Updated to v3 capacitor https://github.com/bazuka5801/native-audio

**Comment by BobCashStory** [comment]
@JuanNitram did you try to remove the silent mode of your phone ?

**Comment by bazuka5801** [comment]
@JuanNitram Fixed in new release 🌟
