### ISSUE TITLE
bug: Incorrect documentation example

### ISSUE THREAD

**Issue by bazuka5801** [capacitor-community/native-audio#25]
**Describe the bug**
Which folder i need to paste audio files.
WHY this is not documentated?
We need add full documentation step-by-step for adding sound to project for android & ios!

In android like example get error `Resource ID not found`
Why? Developers write incorrect examples (worked without file extension).
Examples must be fully tested, because new devs in capacitor do not deeply qualified in platform structure!

**Comment by bazuka5801** [comment]
Use this plugin https://github.com/bazuka5801/native-audio

**Comment by gillarf** [comment]
Thanks @bazuka5801. How do I include your fork in my project? I tried this in my package.json:

"@capacitor-community/native-audio": "git+https://github.com/bazuka5801/native-audio.git"

but when I run npx cap sync I get: 
[!] No podspec found for `CapacitorCommunityNativeAudio` in `../../node_modules/@capacitor-community/native-audio`

**Comment by gillarf** [comment]
I'll just answer myself here - I deleted the old plugin and installed this one with 

npm i git+https://github.com/bazuka5801/native-audio.git -save

**Comment by gillarf** [comment]
Thanks for the hard work @bazuka5801 - I am still having difficulties playing audio files with your fork. 

I placed my audio file as assets/sound/WhistleBlast.m4a

And then loaded the sound file:
    NativeAudio.preloadSimple({
      assetPath: "assets/sound/WhistleBlast.m4a",
      assetId: "whistle",
    });

But got this message in Xcode:

[error] - Unhandled Promise rejection: Asset Path is missing - assets/sound/TMs1_Task_No4_v1a.m4a ; Zone: <root> ; Task: null ; Value: {"message":"Asset Path is missing - assets/sound/WhistleBlast.m4a","errorMessage":""} fromNative@user-script:2:224:23

Any help much appreciated

**Comment by gillarf** [comment]
> Use this plugin https://github.com/bazuka5801/native-audio

Thanks for the hard work @bazuka5801 - I am still having difficulties playing audio files with your fork.

I placed my audio file as assets/sound/WhistleBlast.m4a

And then loaded the sound file:
NativeAudio.preloadSimple({
assetPath: "assets/sound/WhistleBlast.m4a",
assetId: "whistle",
});

But got this message in Xcode:

[error] - Unhandled Promise rejection: Asset Path is missing - assets/sound/TMs1_Task_No4_v1a.m4a ; Zone: ; Task: null ; Value: {"message":"Asset Path is missing - assets/sound/WhistleBlast.m4a","errorMessage":""} fromNative@user-script:2:224:23

Any help much appreciated

**Comment by bazuka5801** [comment]
@gillarf check with wav, and use preloadComplex, preload simple bad works

**Comment by gillarf** [comment]
> @gillarf check with wav, and use preloadComplex, preload simple bad works

Thanks I tried this but I still get Asset path is missing. I am doing this in a Capacitor 2 project.
assets sits in src alongside app folder. I tried 'assets/sound/sample1.wav' and '/assets/sound/sample1.wav'

    NativeAudio.preloadComplex({
      assetPath: 'assets/sound/sample1.wav',
      assetId: 'music',
      volume: 1.0,
      audioChannelNum: 1,
      isUrl: false
    });

    NativeAudio.play({
      assetId: "music",
    });

**Comment by Boosten** [comment]
This plugin does not support loading files from the assets directory, at least not at both platforms. 
On iOS you can get it to work to change your assetPath to `public/assets/sound/sample1.wav` when I'm right. On Android it's always looking at the `res/raw` directory of your native Android project. So you should put your files over there to make it work.

Please also check this issue: https://github.com/capacitor-community/native-audio/issues/9

**Comment by bazuka5801** [comment]
Fixed in new release!
