### ISSUE TITLE
Android cannot find resource

### ISSUE THREAD

**Issue by mikelhamer** [capacitor-community/native-audio#26]
**Describe the bug**
In an Ionic Angular project, the following method call in NativeAudio.java always returns 0.

`      int identifier = ctx
        .getResources()
        .getIdentifier(assetPath, "raw", this.getContext().getPackageName());`

**To Reproduce**
1. Create a new Ionic 5 Angular app
2. Create a directory assets/audio and put an mp3 file in it
3. Install this plugin + cap sync
4. Try to load the file with NativeAudio.simpleLoad()

**Expected behavior**
The audio plays

**Screenshots**
![image](https://user-images.githubusercontent.com/10012080/113644986-0168d980-9654-11eb-9ba8-a67698ceb700.png)
![image](https://user-images.githubusercontent.com/10012080/113645021-10e82280-9654-11eb-8b91-692d1755683b.png)

**Additional context**
I have tried this with every combination of directory paths I can think of. public/assets/audio, app/src/main/assets/public/assets/audio, just audio/, with and without filetype suffix, etc. No matter what I put there, it can't find the resource and returns 0.

I have even confirmed that this statement returns my "errorbeep.mp3"
`ctx.getResources().getAssets().list("public/assets/audio");`

But even still, it always results in this error

`Sending plugin error: {"save":false,"callbackId":"24202082","pluginId":"NativeAudio","methodName":"preloadSimple","success":false,"error":{"message":"Resource ID #0x0"}}`

**Comment by anandsathe67** [comment]
At the end of my tether with this issue. Tried everything just as @mikelhamer  did. Anyone who can help ?

**Comment by gillarf** [comment]
I managed to get it working (on iOS anyway, untested in Android) using a fork of this plugin

This plugin:
https://github.com/bazuka5801/native-audio

I had similar issues, which I was helped with here:
https://github.com/capacitor-community/native-audio/issues/25

In short, use the complex method for loading, and the files on iOS are in public/assets and on Android in res/assets

**Comment by anandsathe67** [comment]
Here is how i got it to work (trial and error)
1. Use resource names instead of file names on Android (Use "errorBeep" instead of "errorBeep.mp3" as the audio assetPath
 - NativeAudio.preloadSimple("errorBeep", "error")
2. Make sure errorBeep.mp3 is present in android/app/src/main/res/raw
@mikelhamer  FYI

**Comment by bazuka5801** [comment]
@mikelhamer Hi)
I fixed this issue and provide some example in readme, not plugin support only capacitor v3.
