### ISSUE TITLE
AppCompatActivity error after updating to Capacitor 3

### ISSUE THREAD

**Issue by andrewl94** [capacitor-community/native-audio#27]
**Describe the bug**

After updating to Capacitor 3 I've been receiving the error bellow. I already used Refactor > Migrate to AndroidX. Before the refactor other plugins were giving similar error, but probably solved by the refactor.
I'm really lost, probably I need to change some reference somewhere, but I had no luck researching that for now. 
______________________________________________________________________________________________________
{{project_dir}}\app\src-capacitor\node_modules\@capacitor-community\native-audio\android\src\main\java\com\getcapacitor\community\audio\NativeAudio.java:54: error: cannot access AppCompatActivity
      .getActivity()
                  ^
  class file for androidx.appcompat.app.AppCompatActivity not found
______________________________________________________________________________________________________

My gradle variables:

    minSdkVersion = 21
    compileSdkVersion = 30
    targetSdkVersion = 30
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion = '7.0.0'

**To Reproduce**
1. Update Capacitor to 3
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android
 - Version sdk 21/ target 30

**Smartphone (please complete the following information):**
 - 

**Additional context**

**Comment by danielehrhardt** [comment]
Something new here?

**Comment by andrewl94** [comment]
I had to go back to using Capacitor 2.4
IMO not worth the trouble v3 for now.

**Comment by wmtkc** [comment]
I was able to get the build to work by adding these lines to the /android/build.gradle file

`ext {
    junitVersion =  project.hasProperty('junitVersion') ? rootProject.ext.junitVersion : '4.12'

// Add here
    androidxAppCompatVersion = project.hasProperty('androidxAppCompatVersion') ? rootProject.ext.androidxAppCompatVersion : '1.2.0'

    androidxJunitVersion =  project.hasProperty('androidxJunitVersion') ? rootProject.ext.androidxJunitVersion : '1.1.1'
    androidxEspressoCoreVersion =  project.hasProperty('androidxEspressoCoreVersion') ? rootProject.ext.androidxEspressoCoreVersion : '3.2.0'
}`

`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':capacitor-android')

// And here
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"

    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
}`

But the plugin code itself doesn't seem to be functioning after a successful build. Calls to `play()` throw the following error on both iOS and Android.

`Uncaught Error: Method not implemented.`

[Howler.js](https://www.npmjs.com/package/howler) seems to do the job in the meantime, if you need to be on Capacitor 3.

**Comment by bazuka5801** [comment]
@andrewl94 If your issue connected with plugin, please send message here.
