### ISSUE TITLE
Looking For Maintainers!

### ISSUE THREAD

**Issue by thomasvidas** [capacitor-community/native-audio#30]
If you are interested in helping maintaining this plugin, you can comment here or contact @ThomasV on the Capacitor Slack. to help you get set up on the Capacitor Community Github org 😄

This plugin is only Capacitor 2.x compatible and will not work with the upcoming Capacitor 3

**Comment by Boosten** [comment]
Maybe @robingenz can help 👍 . He has quite a good track record in maintaining Capacitor plugins 😎.

**Comment by robingenz** [comment]
Thank you for the flowers! 😄  @Boosten 
Currently I have many private projects and therefore not too much time.
One project should be "finished" in the next few weeks.
So I will keep an eye on this issue.

**Comment by riderx** [comment]
@bazuka5801 look to have the most advanced fork ! he did the capacitor v3 support already

**Comment by bazuka5801** [comment]
@riderx Thanks!)
@thomasvidas Now I worked for project what need this plugin work correctly for cap3.
I can maintain it with fresh docgen from capacitor 😉

**Comment by thomasvidas** [comment]
@bazuka5801 has reached out to me and I've added him as a maintainer for this repo 🎉  So I'll go ahead and close this issue

**Comment by riderx** [comment]
Thanks @thomasvidas @bazuka5801 !
Cannot wait to use the next update :)
