### ISSUE TITLE
Capacitor v3 no sound

### ISSUE THREAD

**Issue by wwwguy** [capacitor-community/native-audio#33]
Having installed the plugin and placed audio files in the Android/iOS location defined, when I call NativeAudio.preload it is returning an error (the error content is just "achievement.mp3"). I'm just including the file name like:

NativeAudio.preload({
    assetId: "achievement",
    assetPath: "achievement.mp3",
    audioChannelNum: 1,
    isUrl: false
});

What am I missing?

**Comment by wwwguy** [comment]
Given the widely reported problems in the cordova plugin related to dealing with changing hardcoded plugin code from "www" to "public" for the file location... one would assume the capacitor community plugin would be explicitly designed to overcome this problem (since one of the main concepts promoted about capacitor is how it's so much more stable than using cordova with ionic). 

Does anyone have this plugin working using ionic capacitor v3 angualar?

**Comment by allankiezel** [comment]
@wwwguy same and no fix found yet. Can't seem to get audio working using any native library with capacitor 3.

**Comment by bazuka5801** [comment]
@wwwguy Hello ✋ 
Please, send a screenshot of your Android Studio/XCode where you placing audio
And full code what working with NativeAudio.

**Comment by bazuka5801** [comment]
@wwwguy Can you convert sounds to wav format and try ?

**Comment by allankiezel** [comment]
@wwwguy @bazuka5801 I just got it working and the issue is the path. You don't need to put the audio files in the locations mentioned in the docs. Just change your `assetPath` to point to the public folder and it works. See my working example below...

`NativeAudio.preload({
  assetId: "swipeLeft",
  assetPath: "public/assets/sounds/swipe-left.mp3"
})`

**Comment by bazuka5801** [comment]
@allankiezel Did you tested it on both platforms (Android & iOS)?

**Comment by wwwguy** [comment]
Thanks for all the feedback. Unfortunately still not working. Some answers to above...

- Currently I'm just running on Android. Will tackle iOS once I have this working.
- I have tried using wav instead of mp3 files, no change, same error.
- Changing the assetPath as mentioned to a "public/" address, no change, same error.

**Comment by wwwguy** [comment]
And the code... app.component.ts

NativeAudio.preload({
    assetId: "achievement",
    assetPath: "test.wav"
}).then(function(){
  console.log("SUCCESS");
}, function(error){
  console.log("ERROR - " + error);
});

Outputs the following error:

ERROR - Error: test.wav

**Comment by bazuka5801** [comment]
@wwwguy try follow with docs and drag-and-drop music sounds to xcode/Android studio like docs in readme

**Comment by wwwguy** [comment]
Yes, correct... from inside Android Studio I have drag/dropped my audio files into:

android/app/src/assets

Then in the preload code, I am just using the filename itself for the assetPath variable. I have also tried various versions of the full path as suggested by @allankiezel

**Comment by allankiezel** [comment]
I haven’t tried android yet as the emulator doesn’t play sounds on my machine. Also, you sample capacitor v3 codebase doesn’t have any actual ionic files to reference.

**Comment by orviljuarez** [comment]
Hi guys! I I'm using the plugin in a Ionic Vue project. I put the files on:
my-ionic-vue-project/android/app/src/main/assets

Then preload the files only with the name: audio1.mp3

NativeAudio.preload({
          assetId: 'audio1',
          assetPath: 'audio1.mp3',
          audioChannelNum: 1,
          isUrl: false
});

And play it:
        NativeAudio.play({
          assetId: 'audio1',
          time: 0.0
        });

I hope this helps somebody.

**Comment by gine** [comment]
I'm using Capacitor v.3

I'm using Ionic5 with ReactJs and Typescript. 

I have copyed sound.mp3 in /public/assets/ then building for android wint ionic build android the builder copy all the content in the right place.

Then you need in your code call:

```
          NativeAudio.preload({
            assetId: "warn",
            assetPath: "public/assets/sound.mp3",
            audioChannelNum: 1,
            isUrl: false
          })
          .then(()=>{
            NativeAudio.setVolume({
              assetId: 'warn',
              volume: 1.0,
            });
  
            NativeAudio.play({
              assetId: 'warn',
              time: 0.0
            })
          });
```

**Comment by wwwguy** [comment]
Bingo. My code was all fine. Big thank you to @orviljuarez for correcting the file location. The instructions here say to place them at:

android/app/src/assets

This is NOT correct (or at least, would not work me). When I move them to:

android/app/src/main/assets

...it starts working fine. Not sure if the instructions here need to be updated or if there is some other factor that would cause this? Anyway, also... for those less familiar using native Android Studio (vs ionic CLI pre-capacitor), make sure to drag and drop audio files inside of Android Studio (much the same as you may already be used to in xCode).
