### ISSUE TITLE
Add listeners to plugin

### ISSUE THREAD

**Issue by csurbier** [capacitor-community/native-audio#36]
Hi,

i would like to receive events from the plugin. I would like to know when a sound is played.
I tried : 

  NativeAudio.addListener('complete', (info: any) => {
      console.log('myPluginEvent complete');
    });

because in swift code you are notifying the plugin: 

 public func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully flag: Bool) {
        NSLog("playerDidFinish")
        self.owner.notifyListeners("complete", data: [
            "assetId": self.assetId
        ])
    }

but on typescript i have an error :

Property 'addListener' does not exist on type 'NativeAudio'.

How can i do it ? 
Thanks

**Comment by dodahoho** [comment]
Until it is properly implemented in the NativeAudio typescript interface definition you can receive events by using type any for NativeAudio like this:

  this.nativeAudioCompleteListener = (NativeAudio as any).addListener(
      'complete',
      (info: any) => {
        console.log('NativeAudio complete was fired');
      },
    );

**Comment by ciekawy** [comment]
#59 is marked as duplicate but there is just `complete` event available in the typings and other events seem to be missing - at least `start`, `stop`, `timeupdate` or `progress`
