### ISSUE TITLE
Can't register plugin in `MainActivity.java`

### ISSUE THREAD

**Issue by kheftel** [capacitor-community/native-audio#4]
**Describe the bug**
Docs describing registering plugin still mention `FirebaseCrashlytics`. I try to register plugin class with `import com.getcapacitor.community.audio.NativeAudio.class;` but package `community` doesn't exist.

**To Reproduce**
1. `npm install @capacitor-community/native-audio`
2. `npx cap sync`
3. `npx cap open android`
4. Android Studio can't find the plugin class to import

**Expected behavior**
Android Studio should find the plugin class.

**Screenshots**
`capacitor.settings.gradle` appears to reference the npm package properly
![image](https://user-images.githubusercontent.com/40306303/86290757-34ed7380-bbab-11ea-91ee-a3fb5553b1cb.png)

Did I get the package/class wrong for import?
![image](https://user-images.githubusercontent.com/40306303/86290856-5b131380-bbab-11ea-80d3-b20428a08e43.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.15
- Android Studio 4.0

**Comment by kheftel** [comment]
After online research (including [this](https://github.com/ionic-team/capacitor/discussions/3128#discussioncomment-29867) and [this](https://stackoverflow.com/questions/29565263/android-studio-how-to-run-gradle-sync-manually)) I was about to uninstall Android Studio, but, either a manual or automatic gradle sync happened and it finds the class now.

Not sure what changed but I'm closing this.

**Comment by leafiy** [comment]
I still have this problem, and I've done reinstall Android studio and Gradle Sync

![image](https://user-images.githubusercontent.com/870449/101219664-4a694b00-36bf-11eb-929e-3570e27d04a8.png)
