### ISSUE TITLE
[Android only] NativeAudio.play() promise doesn't trigger

### ISSUE THREAD

**Issue by Merwan1010** [capacitor-community/native-audio#45]
```js
    NativeAudio.play({
      assetId: fileName,
      time: 0,
    })
      .then((onfulfilled) => {
        console.log(`${fileName} playing...`);
      })
      .catch((e) => console.log(`error playing ${fileName}`, e));
```

on iOS the promise is trigger properly, however on Android, when the file is playing nothing shows up.

<img width="1209" alt="Screen Shot 2021-11-12 at 11 50 32" src="https://user-images.githubusercontent.com/42877823/141400714-e227984b-0a96-40bd-9e7b-a2e82b616dc2.png">

<img width="1218" alt="Screen Shot 2021-11-12 at 11 49 40" src="https://user-images.githubusercontent.com/42877823/141400626-186cb47d-0ff9-4889-9142-aca12d8d7c87.png">

**Comment by danielehrhardt** [comment]
Same.

**Comment by arielhasidim** [comment]
same, play and also loop.

**Comment by francoisduchemin** [comment]
I have the same issue on Android...

**Comment by Lucas-Wanat** [comment]
Same.

**Comment by antonymarion** [comment]
Hi @bazuka5801,

Do you have any workaround for this on Android ?

Regards,
Antony
