### ISSUE TITLE
Play different audio files in the app

### ISSUE THREAD

**Issue by pvsantosh** [capacitor-community/native-audio#46]
How to know when the audio is done playing? So that i can unload the file. I'm having issue in playing different audio clips at different places of the application. It is always playing the firstly loaded audio file.

Anybody know how to handle this?

**Comment by akhromieiev** [comment]
+1

**Comment by stefanhuber** [comment]
I guess the only way to check if the audio is done playing `getCurrentTime() == getDuration()` or similar...

**Comment by bazuka5801** [comment]
@pvsantosh I added support for `content:/....` files in `3.0.2` version

**Comment by jcesarmobile** [comment]
I've published 5.0.1 that adds types for the existing `complete` listener that fires when the audio finish, so you can use that
