### ISSUE TITLE
Support for http streaming audio?

### ISSUE THREAD

**Issue by claudiomerli** [capacitor-community/native-audio#56]
**Is your feature request related to a problem? Please describe.**
I actually need a feature to setup a streaming for a web radio, which have an https url (https://onair20.xdevel.com/proxy/nslradiotv?mp=/;stream)

**Describe the solution you'd like**
All actually present features but with possibility to setup an http url as of assetPath

**Describe alternatives you've considered**
Cordova Plugin media-streaming

**Comment by jcesarmobile** [comment]
duplicate of https://github.com/capacitor-community/native-audio/issues/16
