### ISSUE TITLE
Add event listeners

### ISSUE THREAD

**Issue by patrickjquinn** [capacitor-community/native-audio#59]
**Is your feature request related to a problem? Please describe.**

There is no method to listen for player state changes making it only useful for async or background sounds.

**Describe the solution you'd like**

an ```addEventListener``` for error, end, start

**Describe alternatives you've considered**
None

**Additional context**
I'd like to wrap this in a promise so I can do something after a sound has finished being played.

**Comment by arturomf** [comment]
Hi, this is an absolute must. Without end listeners, it's not possible to queue sounds for example.

**Comment by kubenstein** [comment]
there is `NativeAudio.addListener("complete", this.onComplete);` but `complete` is the only event out there (and its not fired when a song is started in `loop` mode). Lack of events, especially `progress` is a bit of a deal breaker for me..

**Comment by jcesarmobile** [comment]
duplciate of https://github.com/capacitor-community/native-audio/issues/36
