### ISSUE TITLE
Why not update to current version of capacitor? 

### ISSUE THREAD

**Issue by alindzon** [capacitor-community/native-audio#70]
I cannot install because I am on Capacitor Core 4.x not 3.x.

**Comment by RaddishIoW** [comment]
Try this fork: https://guthub.com/Cap-Go/native-audio

**Comment by MatKershaw3708** [comment]
Just tried the Cap-Go plug in and it works great in Capacitor 4. Many thanks to the maintainers of **that** plug-in.

**Comment by WhippyM** [comment]
The CapGo Plugin was not working, so I updated this one, but need somebody to review and maybe merge: https://github.com/capacitor-community/native-audio/pull/80

**Comment by jcesarmobile** [comment]
version 4.0.0 has been released with Capacitor 4 support
version 5.0.0 has been released with Capacitor 5 support
