### ISSUE TITLE
Need maintainers?

### ISSUE THREAD

**Issue by RaddishIoW** [capacitor-community/native-audio#71]
Hi there,

I notice this plugin hasn't been updated in a while... would it be a good idea to add some more maintainers to help?

**Comment by riderx** [comment]
I made a fork https://github.com/Cap-go/native-audio and will pay maintainer with Capgo business

**Comment by jcesarmobile** [comment]
You can join the capacitor community in discord and ask there if you are interested, I just updated a few things and merged an user PR that added Capacitor 6 support
