### ISSUE TITLE
Audio is not played

### ISSUE THREAD

**Issue by Lucas-Wanat** [capacitor-community/native-audio#74]
**Describe the bug**
When preload() is executed, it returns an error:

**To Reproduce**
- Execute the beep function when preloading, the error occurs

![Captura de tela 2023-01-17 092019](https://user-images.githubusercontent.com/98159692/212897174-02dafcf3-65bd-49e9-bd6c-1910717b0005.png)
![image](https://user-images.githubusercontent.com/98159692/212900764-44de390e-8405-44db-820a-e45d09e360bf.png)

`Sending plugin error:{"save":false,"callbackId":"18192255","pluginId":"NativeAudio","methodName":"preload","success":false,"error":{"message":"androidappsrcassetsaudio\beep_erro.wav"}}`

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: samsung (tablet)
 - OS: android 11
 - Browser google

**Additional context**
using capacitor 3.5.1, Cordova 10.1.2 and I've tried different audio locations but it didn't work

Thanks in advance.

Ps: the community must improve.

**Comment by bazuka5801** [comment]
@Lucas-Wanat In the javascript part, you can pass the assetPath as a filename instead of a fullpath.

**Comment by Lucas-Wanat** [comment]
> @Lucas-WanatNa parte do javascript, você pode passar o assetPath como um nome de arquivo em vez de um caminho completo. Isso pode resolver o problema.

@bazuka5801 Eu vou tentar isso, antes eu já havia tentado, e acabou que não deu certo, devo colocar a extensão do arquivo ou somente o nome? Também tentei isso, e no meu projeto não existe uma pasta src na pasta android, acho que o local, mostrado na documentação não seria o correto para mim.

**Comment by Lucas-Wanat** [comment]
> @Lucas-Wanat In the javascript part, you can pass the assetPath as a filename instead of a fullpath. This might solve the problem.

@bazuka5801 I'm going to try that, I had already tried that before, and it ended up not working, should I put the file extension or just the name? I also tried that, and in my project there is no src folder in the android folder, I think the location, shown in the documentation would not be correct for me.

**Comment by Lucas-Wanat** [comment]
@bazuka5801 returning to inform that it didn't work, I just put the name (beep_correto.wav) and it didn't work

**Comment by Lucas-Wanat** [comment]
A new error occurred, after testing what I did as said in the previous comment in the edit, it returned this error:

![image](https://user-images.githubusercontent.com/98159692/213205109-6ff5e1b7-7a91-4931-982b-37ea37676c20.png)

The code:

![image](https://user-images.githubusercontent.com/98159692/213205273-3767c589-536f-4efc-9017-df54a542f5bf.png)
