### ISSUE TITLE
on android it doesn't work

### ISSUE THREAD

**Issue by LuisAlvaradoMtz97** [capacitor-community/native-audio#97]
I have a method which is responsible for playing the sound, place the mp3 file in the folders indicated in the documentation, when compiling on the web if the sound plays successfully, but when synchronizing the android application nothing is heard, now I tried with previous versions and I didn't get any results.

The following is the declaration I have at the beginning of my component
![image](https://github.com/capacitor-community/native-audio/assets/135260797/f5e5d0b2-d43a-4722-9c74-b40b98483147)

Once the component is mounted I preload the .mp3 file
![image](https://github.com/capacitor-community/native-audio/assets/135260797/9a210bf8-c852-4813-96df-548005de39de)

Below I attach the button code and the method that calls the sound
![image](https://github.com/capacitor-community/native-audio/assets/135260797/48c958b5-edb8-4614-9df3-356e19481e24)

![image](https://github.com/capacitor-community/native-audio/assets/135260797/71a630a0-e79f-41b3-adc8-2416330a2e37)

I am attaching the location of the file in my ionic project
![image](https://github.com/capacitor-community/native-audio/assets/135260797/a1e857af-b94a-4261-84e9-b3465b032d1d)

Below I show you where I have the file for the Android application located.
![image](https://github.com/capacitor-community/native-audio/assets/135260797/3c45429a-5709-4dbc-85ea-7792dfdd9244)

I don't have any problems on the website, since it works perfectly, but on Android is where I haven't been able to play the sound

I attach the result that Android Studio returns when clicking the button
![image](https://github.com/capacitor-community/native-audio/assets/135260797/e5c14143-4196-4b57-9f9c-d991ca2875a6)

**Smartphone :**
 - Device: Samsung A51
 - OS: Android 13

I hope you can help me, or detect what my error is.

**Comment by ASHBAW** [comment]
Any resolution to this. I am also having the issue where it is working for the web but not for Android.

I have tried a lot of locations.

The documentation has the following location for Android:

Andoid: android/app/src/assets 

here is my corresponding code:

`  constructor() {
    NativeAudio.preload({
        assetId: "green_noise",
        assetPath: "green_noise.mp3",
        audioChannelNum: 1,
        isUrl: false
    }).catch(err => console.log(err));
  }`

The last one I tried the following per the above suggestion which did not help:

` NativeAudio.preload({
        assetId: "noise",
        assetPath: "public/assets/sounds/green_noise.mp3",
        audioChannelNum: 1,
        isUrl: false
    }).catch(err => console.log(err));`

With the .wav file at the following location:

![Screenshot 2024-09-03 at 7 27 51 AM](https://github.com/user-attachments/assets/8ea8c979-aa5d-4f26-bbdb-f051795b1ac1)

Any insight as to what I am doing wrong would be greatly appreciated.

Thanks
